### ISSUE TITLE
srcdoc polyfill

### ISSUE THREAD

**Issue by NeXTs** [edenspiekermann/iframify#12]
Consider integrating [srcdoc-polyfill](https://github.com/jugglinmike/srcdoc-polyfill) to handle lack of srcdoc in weak browsers.

It's tiny and pretty well tested.

**Comment by KittyGiraudel** [comment]
Hey there,

The problem is not to polyfill `srcdoc` which turns out to be quite easy. The problem is that when polyfilled (as far as I know, at least), you start encountering issues with CORS policy, because of the difference in protocols between the parent window and the embedded document.

**Comment by NeXTs** [comment]
Hey

Okay, I got it.
Just gave an idea

**Comment by KittyGiraudel** [comment]
That is worth another try though. Maybe I can find a way.

**Comment by aPoCoMiLogin** [comment]
You will not get any CORS error when created iframe will be created with `src` set to `javascript:false` or `about:blank` this will trick browser to not set any protocol, where the first way is better, because will work in even older IE's. Give it a try, and you will see that it will works. Using similar way to creating iframe with "widget" in lots of different websites, with IE8/chrome 4/ff 3.5/opera 12 compatibility.

**Comment by KittyGiraudel** [comment]
Interesting. When I tried local iframes at first, I did it with a encoded data passed directly into the URL as a `data:text/html;charset=utf-8,`. And I had CORS issues.

**Comment by aPoCoMiLogin** [comment]
Yeah this will not work in some browsers, like IE (data uri). The trick is about first set `src`, then set `srcdoc` and then check if `srcdoc` exists in iframe element, if not, set the `src` again, as `javascript: window.frameElement.getAttribute('srcdoc');` then check if `contentWindow` is not null/empty (it will be created in IE9) and force document to reload `location` with new url. 

In short: 

``` javascript
!(function(){

    'use strict';

    var iframe = document.createElement('iframe');
    iframe.setAttribute('src',  'javascript:false');
    iframe.setAttribute('srcdoc', '<!DOCTYPE html><html><head></head><body></body></html>');

    // polyfill
    if(!('srcdoc' in document.createElement('iframe')))
    {
        var contentUrl = "javascript: window.frameElement.getAttribute('srcdoc');";

        iframe.setAttribute('src',  contentUrl);

        // compatibility with IE9
        if(iframe.contentWindow)
        {
            iframe.contentWindow.location = contentUrl;
        }
    }

    document.body.appendChild(iframe);

})();
```

**Comment by KittyGiraudel** [comment]
I added a comment to the README about the polyfill. I am not keen to add the polyfill as part of iframify. The reason behind this is that I assume most users will include iframify as part as a styleguide which is unlikely to be viewed on IE. For users wanting their document to work the same on IE, they can include the polyfill.

What do you think?

**Comment by aPoCoMiLogin** [comment]
Depends on your preferences, because you have right that most webdev's will not use IE, except some testing, so there is no sense to make it working in IE's or other old browser. 

Just commented only to show that it is possible to avoid CORS, as a useful tip to keep in mind for the future. And yeah if someones wants make it works for IE, then including polyfill linked in first comment should do the job.

**Comment by KittyGiraudel** [comment]
Really appreciate your input! :)
